version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: digiify-nginx-proxy_web_1
      APP_PORT: 3100
    
    web:
      image: 'jc21/nginx-proxy-manager:latest'
      restart: unless-stopped
      ports:
        # These ports are in format <host-port>:<container-port>
        - '80:80' # Public HTTP Port
        - '443:443' # Public HTTPS Port
        - '8081:8081' # Admin Web Port
        # Add any other Stream port you want to expose
        # - '21:21' # FTP
      environment:
        # Mysql/Maria connection parameters:
        DB_MYSQL_HOST: "db"
        DB_MYSQL_PORT: 3306
        DB_MYSQL_USER: "proxymanager"
        DB_MYSQL_PASSWORD: "9T84@AxmG"
        DB_MYSQL_NAME: "nginx"
        # Uncomment this if IPv6 is not enabled on your host
        # DISABLE_IPV6: 'true'
      volumes:
        - ${APP_DATA_DIR}/data/nginx:/data
        - ${APP_DATA_DIR}/letsencrypt:/etc/letsencrypt
      depends_on:
        - db

    db:
      image: 'jc21/mariadb-aria:latest'
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: 'pz$2J9Qnz'
        MYSQL_DATABASE: 'nginx'
        MYSQL_USER: 'proxymanager'
        MYSQL_PASSWORD: '9T84@AxmG'
        MARIADB_AUTO_UPGRADE: '1'
      volumes:
        - ${APP_DATA_DIR}/mysql:/var/lib/mysql